name: Build PDF

on:
  push:
    branches: [main, master]

jobs:
  render_cv:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Set up Pandoc and pdflatex
      uses: r-lib/actions/setup-pandoc@v1

    - name: Install dependencies
      run: |
        Rscript -e "install.packages('dplyr')"
        Rscript -e "install.packages('rmarkdown')"
        Rscript -e "install.packages('vitae')"

    - name: Build PDF
      run: Rscript -e "rmarkdown::render('btmonier_cv.Rmd')"

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v2
      with:
        name: pdf-output
        path: btmonier_cv.pdf

    - name: Commit files
      run: |
        git config --local core.autocrlf false
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"
        git config --local user.name "${{ github.actor }}"
        git add *.pdf && git add --renormalize *.pdf
        git pull origin ${{ github.head_ref }} --autostash --rebase -X ours
        git commit --allow-empty -am "AUTO-GH ACTION: ${{ github.workflow }}"
        NO_PAGER=1 git --no-pager diff HEAD^

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: ${{ github.head_ref }}

        github_token: ${{ secrets.GITHUB_TOKEN }}
