name: Build PDF

on:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PanDoc
      uses: r-lib/actions/setup-pandoc@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install dependencies
      run: |
        Rscript -e "install.packages('rmarkdown')"
        Rscript -e "install.packages('vitae')"
        Rscript -e "install.packages('dplyr')"

    - name: Build PDF
      run: Rscript -e "rmarkdown::render('btmonier_cv.Rmd')"

    - name: Upload PDF artifact
      uses: actions/upload-artifact@v2
      with:
        name: pdf-output
        path: ./btmonier_cv.pdf
